# Generated by Django 4.2.23 on 2025-08-21 19:41

import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content_short',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Краткое содержание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Содержание'),
            preserve_default=False,
        ),
    ]
