# Generated by Django 4.2.23 on 2025-08-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_content_short_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Основное оописание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_short',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Красткое  описание'),
        ),
    ]
