"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-tigran-3op!1*$3ot!jsf+$z459u&o5@3ui_cm_1k7w%svo)dcp0bsr+4"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
    "news",
    "about",
    "portfolio",
    "reviews",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.site_metadata",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# Настройки для разработки (development)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Пути, откуда collectstatic будет собирать статические файлы
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# Альтернатива с pathlib (раскомментируйте, если используете этот подход)
# STATICFILES_DIRS = [BASE_DIR / "static"]

# Куда collectstatic соберет ВСЕ статические файлы для продакшена
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # Важно: это строка, а не список!
# Альтернатива с pathlib:
# STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# JAZZMIN SETTINGS
JAZZMIN_SETTINGS = {
    "site_title": "DpiT-CMS",
    "site_title_small": "DpiT-CMS",
    "site_header": "DpiT-CMS",
    "site_brand": "DpiT-CMS",
    "site_brand_small": "DpiT-CMS",
    "site_logo": "images/logo.png",
    "site_logo_classes": "img-circle",
    "welcome_sign": "Добро пожаловать в админку DpiT-CMS",
    "enable_reports": True,
    # "search_model": ["auth.User", "news.News", "portfolio.Portfolio"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": [
        "main",
        "news",
        "about",
        "portfolio",
        "reviews",
        "auth",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.SiteMetadata": "fas fa-cog",
        "news.NewsCategory": "fas fa-folder",
        "news.News": "fas fa-newspaper",
        "about.AboutPage": "fas fa-info-circle",
        "portfolio.PortfolioCategory": "fas fa-folder-open",
        "portfolio.Portfolio": "fas fa-briefcase",
        "reviews.Review": "fas fa-comments",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

# JAZZMIN UI SETTINGS
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "navbar_small_text": True,
    "footer_small_text": True,
}
