# Generated by Django 4.2.23 on 2025-08-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemetadata',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitemetadata',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание сайта'),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
