# Generated by Django 4.2.23 on 2025-08-19 18:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('image', models.ImageField(upload_to='about/', verbose_name='Изображение')),
                ('seo_title', models.CharField(max_length=200, verbose_name='SEO Заголовок')),
                ('seo_keywords', models.CharField(max_length=200, verbose_name='SEO Ключевые слова')),
                ('seo_description', models.CharField(max_length=255, verbose_name='SEO Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Страница о нас',
                'verbose_name_plural': 'Страницы о нас',
            },
        ),
    ]
